
services:
  # 🛢 PostgreSQL Database
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🔑 Keycloak Authentication Server
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8484:8080"  # ✅ Changed from 8282 to 8282 to avoid conflicts
    depends_on:
      - postgres

  # 🖥 .NET Core Backend API
  pos-backend:
    build:
      context: ./pos-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=pos_system;Username=pos_user;Password=rj200100p"
      Keycloak__Authority: "http://keycloak:8080/realms/pisval-pos-realm"  # ✅ Internal communication remains on 8080
      Keycloak__ClientId: "pos-backend"
      Keycloak__ClientSecret: "mKvMzX6Klgc4yMFRmqs3H3OtSRwa0B3b"
    ports:
      - "5200:5200"
    depends_on:
      - postgres
      - keycloak

  # 🌐 Next.js Frontend
  pos-system:
    build:
      context: ./pos-system
      dockerfile: Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: "http://pos-backend:5107"
      NEXT_PUBLIC_KEYCLOAK_URL: "http://localhost:8383"  # ✅ Updated for frontend usage
    ports:
      - "3001:3000"
    depends_on:
      - pos-backend

volumes:
  postgres_data:
